version: '3.9'

services:
  redis:
    image: "bitnami/redis:latest"
    container_name: redis_server
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis_pass
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local